# Generated by Django 3.2.5 on 2022-05-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ccontactme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=7000)),
            ],
        ),
    ]
