# Generated by Django 3.2.5 on 2022-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addprojects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(default=' ', max_length=10000)),
                ('head', models.CharField(default=' ', max_length=10000)),
                ('link', models.CharField(default=' ', max_length=10000)),
            ],
        ),
    ]
