# Generated by Django 3.2.5 on 2022-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0003_rename_tech_addprojects_techdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=' ', upload_to='myianges')),
                ('Address', models.CharField(default=' ', max_length=100000)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField(default=0)),
                ('Skills', models.CharField(default=' ', max_length=100000)),
                ('cn', models.CharField(default=' ', max_length=10000)),
            ],
        ),
    ]
