# Generated by Django 3.2.5 on 2022-05-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0004_mydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
