# Generated by Django 3.2.5 on 2022-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincode', '0005_mydata_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='cn',
            new_name='Collegename',
        ),
        migrations.AddField(
            model_name='mydata',
            name='name',
            field=models.CharField(default=' ', max_length=10000),
        ),
    ]
